groups:
    - bash
    - developer
recipes:
    global:
        - dotfiles::sshconfig
    mac_os_x:
        - applications::omnigraffle
        - applications::launchrocket
        - sudoalt::default
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_position_the_dock_on_the_left_side
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_animation_when_hiding_showing_the_dock
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::mail_when_searching_do_not_include_trash
        - osxdefaults::mail_copy_email_addresses_instead_of_names_in_mail
        - osxdefaults::set_computer_name
attributes:
    sublime_text_packages:
        -
            name: SideBarEnhancements
            source: https://github.com/titoBouzout/SideBarEnhancements
            branch: st3
        -
            name: GitGutter
            source: https://github.com/jisaacks/GitGutter.git
            branch: master
        -
            name: SCSS
            source: https://github.com/MarioRicalde/SCSS.tmbundle.git
            branch: SublimeText2
        -
            name: BracketHighlighter
            source: https://github.com/facelessuser/BracketHighlighter.git
            branch: ST3
        -
            name: PHP-Twig
            source: https://github.com/Anomareh/PHP-Twig.tmbundle.git
            branch: master
        -
            name: Theme - Aqua
            source: https://github.com/cafarm/aqua-theme.git
            branch: master
        -
            name: Base16
            source: https://github.com/chriskempson/base16-textmate.git
            branch: master
        -
            name: ApplySyntax
            source: https://github.com/facelessuser/ApplySyntax.git
            branch: ST3
        -
            name: Theme - Flatland
            source: git://github.com/thinkpixellab/flatland.git
            branch: master
    dotfiles:
        vimusers:
            - root
            - roderik
        kdeploy:
            hostname: dev
        vim:
            bundle:
                - sleuth: git://github.com/tpope/vim-sleuth.git
                - sensible: git://github.com/tpope/vim-sensible.git
                - gitgutter: git://github.com/airblade/vim-gitgutter.git
                - airline: https://github.com/bling/vim-airline
                - syntastic: git://github.com/scrooloose/syntastic.git
                - nerdtree: https://github.com/scrooloose/nerdtree.git
                - vim-css-color: https://github.com/ap/vim-css-color
    git:
        name: Roderik van der Veer
        email: roderik.van.der.veer@kunstmaan.be
    osxdefaults:
        computername: Mir
    authorization:
        sudo:
            users:
                - roderik
            passwordless: true
            include_sudoers_d: true
    homebrewalt:
        cask_apps:
            - google-drive
            - things
            - dropbox
            - evernote
            - istat-menus
            - kaleidoscope
            - alfred
            - totalfinder
            - spotify
            - bartender
            - hazel
            - sonos
            - caffeine
            - tower
            - vlc
            - handbrake
            - slack
            - flashlight
            - couleurs
            - vagrant-manager
            - cord
