recipes:
    global:
        - applications::homebrew-bash
        - dotfiles::bashrc
        - dotfiles::inputrc
        - applications::bash
attributes:
    homebrewalt:
        apps:
            - bash-completion2
